"""Initial schema: all tables, constraints, and indexes

Implements `docs/data-dictionary.md` §2–§4 (tables), §5 (controlled vocabularies as
VARCHAR + CHECK, per ADR-020), §6 (BIGINT identity keys, TIMESTAMPTZ, money types),
§8 (check constraints), and §9 (indexing considerations).

Written by hand rather than autogenerated: no database was reachable at authoring
time. `alembic check` against a fresh `upgrade head` is what proves it matches
`db_models.Base.metadata` — if that reports pending operations, this file is wrong.

Two deliberate omissions, both reasoned in the data dictionary:

* `archived_requests.completed_at >= service_requests.scheduled_datetime` (§8) spans
  two tables, so it cannot be a CHECK. §8 offers "trigger or app layer"; it is left
  to the generator's validation suite and the QA agent's invariant checks instead. A
  trigger would add invisible behaviour, fight bulk generator inserts, and duplicate
  a check that already belongs to QA.
* §9 lists an index on `service_feedback(request_id)`. That column carries a UNIQUE
  constraint whose backing btree index already serves those lookups, so a second
  index would be dead weight the planner never chooses.

Revision ID: 0f3c81a47b21
Revises:
Create Date: 2026-09-20 12:00:00.000000+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0f3c81a47b21"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ----------------------------------------------------------------- #
    # §2 Reference tables
    # ----------------------------------------------------------------- #
    op.create_table(
        "accounts",
        sa.Column("account_id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("account_code", sa.String(length=20), nullable=False),
        sa.Column("account_name", sa.String(length=255), nullable=False),
        sa.Column("account_status", sa.String(length=32), nullable=False),
        sa.Column("contract_tier", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("account_id", name="pk_accounts"),
        sa.CheckConstraint(
            "account_status IN ('active', 'inactive', 'prospect')",
            name="ck_accounts_account_status",
        ),
        sa.CheckConstraint(
            "contract_tier IN ('standard', 'priority', 'enterprise')",
            name="ck_accounts_contract_tier",
        ),
        sa.UniqueConstraint("account_code", name="uq_accounts_account_code"),
    )

    op.create_table(
        "internal_users",
        sa.Column("user_id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("user_role", sa.String(length=32), nullable=False),
        sa.Column("user_status", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name="pk_internal_users"),
        sa.CheckConstraint(
            "user_role IN ('dispatcher', 'supervisor', 'billing_clerk', 'qa_analyst')",
            name="ck_internal_users_user_role",
        ),
        sa.CheckConstraint(
            "user_status IN ('active', 'inactive')",
            name="ck_internal_users_user_status",
        ),
    )

    op.create_table(
        "technicians",
        sa.Column("technician_id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("technician_status", sa.String(length=32), nullable=False),
        sa.Column("home_region", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("technician_id", name="pk_technicians"),
        sa.CheckConstraint(
            "technician_status IN ('active', 'on_leave', 'terminated')",
            name="ck_technicians_technician_status",
        ),
    )

    op.create_table(
        "contacts",
        sa.Column("contact_id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("contact_role", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("contact_id", name="pk_contacts"),
        sa.CheckConstraint(
            "contact_role IN ('site_contact', 'billing_contact', 'account_admin', 'other')",
            name="ck_contacts_contact_role",
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.account_id"],
            name="fk_contacts_account_id_accounts",
        ),
    )

    op.create_table(
        "locations",
        sa.Column("location_id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("site_name", sa.String(length=100), nullable=True),
        sa.Column("street_address", sa.String(length=255), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("zip_code", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("location_id", name="pk_locations"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.account_id"],
            name="fk_locations_account_id_accounts",
        ),
    )

    op.create_table(
        "technician_skills",
        sa.Column("technician_id", sa.BigInteger(), nullable=False),
        sa.Column("skill", sa.String(length=32), nullable=False),
        sa.Column("proficiency", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("technician_id", "skill", name="pk_technician_skills"),
        sa.CheckConstraint(
            "skill IN ('network', 'hardware', 'cabling', 'security_systems', 'power_systems')",
            name="ck_technician_skills_skill",
        ),
        sa.CheckConstraint(
            "proficiency IN ('certified', 'experienced', 'trainee')",
            name="ck_technician_skills_proficiency",
        ),
        sa.ForeignKeyConstraint(
            ["technician_id"],
            ["technicians.technician_id"],
            name="fk_technician_skills_technician_id_technicians",
        ),
    )

    # ----------------------------------------------------------------- #
    # §3 Core operational tables
    # ----------------------------------------------------------------- #
    op.create_table(
        "service_requests",
        sa.Column("request_id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("reservation_number", sa.String(length=20), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("location_id", sa.BigInteger(), nullable=False),
        sa.Column("contact_id", sa.BigInteger(), nullable=False),
        sa.Column("service_type", sa.String(length=32), nullable=False),
        sa.Column("priority_tier", sa.String(length=32), nullable=False),
        sa.Column("equipment_unit_count", sa.Integer(), nullable=False),
        # §6 governs over the bare TIMESTAMP in the §3 table: naive timestamps
        # produce wrong SLA math and wrong hour-of-day seasonality.
        sa.Column("scheduled_datetime", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("sla_window_minutes", sa.Integer(), nullable=False),
        sa.Column("assigned_technician_id", sa.BigInteger(), nullable=True),
        sa.Column("payment_method", sa.String(length=32), nullable=False),
        sa.Column("request_status", sa.String(length=32), nullable=False),
        sa.Column("parent_request_id", sa.BigInteger(), nullable=True),
        sa.Column("dispatched_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("cancellation_reason", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("request_id", name="pk_service_requests"),
        sa.CheckConstraint(
            "service_type IN ('install', 'repair', 'maintenance', 'inspection', 'upgrade')",
            name="ck_service_requests_service_type",
        ),
        sa.CheckConstraint(
            "priority_tier IN ('standard', 'urgent', 'critical')",
            name="ck_service_requests_priority_tier",
        ),
        sa.CheckConstraint(
            "request_status IN ('open', 'dispatched', 'en_route', 'in_progress', "
            "'completed', 'cancelled')",
            name="ck_service_requests_request_status",
        ),
        sa.CheckConstraint(
            "payment_method IN ('credit_card', 'direct_bill', 'ach', 'check')",
            name="ck_service_requests_payment_method",
        ),
        sa.CheckConstraint(
            "cancellation_reason IN ('client_cancelled', 'client_no_show', "
            "'resource_unavailable', 'duplicate', 'other')",
            name="ck_service_requests_cancellation_reason",
        ),
        sa.CheckConstraint(
            "equipment_unit_count > 0",
            name="ck_service_requests_equipment_unit_count_positive",
        ),
        sa.CheckConstraint(
            "sla_window_minutes > 0",
            name="ck_service_requests_sla_window_minutes_positive",
        ),
        sa.CheckConstraint(
            "(cancelled_at IS NOT NULL) = (request_status = 'cancelled')",
            name="ck_service_requests_cancelled_at_matches_status",
        ),
        sa.CheckConstraint(
            "cancellation_reason IS NULL OR request_status = 'cancelled'",
            name="ck_service_requests_cancellation_reason_requires_cancelled",
        ),
        sa.CheckConstraint(
            "parent_request_id IS DISTINCT FROM request_id",
            name="ck_service_requests_parent_not_self",
        ),
        sa.UniqueConstraint("reservation_number", name="uq_service_requests_reservation_number"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.account_id"],
            name="fk_service_requests_account_id_accounts",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.location_id"],
            name="fk_service_requests_location_id_locations",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.contact_id"],
            name="fk_service_requests_contact_id_contacts",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_technician_id"],
            ["technicians.technician_id"],
            name="fk_service_requests_assigned_technician_id_technicians",
        ),
        # Self-reference for repeat visits; Postgres accepts this inside CREATE TABLE.
        sa.ForeignKeyConstraint(
            ["parent_request_id"],
            ["service_requests.request_id"],
            name="fk_service_requests_parent_request_id_service_requests",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["internal_users.user_id"],
            name="fk_service_requests_created_by_user_id_internal_users",
        ),
    )
    op.create_index(
        "ix_service_requests_scheduled_datetime",
        "service_requests",
        ["scheduled_datetime"],
    )
    op.create_index(
        "ix_service_requests_account_id_scheduled_datetime",
        "service_requests",
        ["account_id", "scheduled_datetime"],
    )
    op.create_index("ix_service_requests_request_status", "service_requests", ["request_status"])
    op.create_index(
        "ix_service_requests_parent_request_id", "service_requests", ["parent_request_id"]
    )

    op.create_table(
        "archived_requests",
        sa.Column("request_id", sa.BigInteger(), nullable=False),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("technician_id", sa.BigInteger(), nullable=False),
        sa.Column("labor_charge", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("parts_charge", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("surcharge_rate", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("payment_method_final", sa.String(length=32), nullable=False),
        sa.Column("payment_status", sa.String(length=32), nullable=False),
        sa.Column("payment_reference", sa.String(length=50), nullable=True),
        sa.Column(
            "archived_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("request_id", name="pk_archived_requests"),
        sa.CheckConstraint(
            "payment_method_final IN ('credit_card', 'direct_bill', 'ach', 'check')",
            name="ck_archived_requests_payment_method_final",
        ),
        sa.CheckConstraint(
            "payment_status IN ('pending', 'paid', 'disputed')",
            name="ck_archived_requests_payment_status",
        ),
        sa.CheckConstraint(
            "labor_charge >= 0", name="ck_archived_requests_labor_charge_non_negative"
        ),
        sa.CheckConstraint(
            "parts_charge >= 0", name="ck_archived_requests_parts_charge_non_negative"
        ),
        sa.CheckConstraint(
            "surcharge_rate >= 0 AND surcharge_rate <= 1",
            name="ck_archived_requests_surcharge_rate_range",
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["service_requests.request_id"],
            name="fk_archived_requests_request_id_service_requests",
        ),
        sa.ForeignKeyConstraint(
            ["technician_id"],
            ["technicians.technician_id"],
            name="fk_archived_requests_technician_id_technicians",
        ),
    )
    op.create_index("ix_archived_requests_completed_at", "archived_requests", ["completed_at"])

    op.create_table(
        "incidents",
        sa.Column("incident_id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("request_id", sa.BigInteger(), nullable=False),
        sa.Column("incident_type", sa.String(length=32), nullable=False),
        sa.Column("incident_status", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("root_cause_category", sa.String(length=32), nullable=True),
        sa.Column("attributed_technician_id", sa.BigInteger(), nullable=True),
        sa.Column("reported_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("reported_by_contact_id", sa.BigInteger(), nullable=False),
        sa.Column("resolved_at", sa.TIMESTAMP(timezone=True), nullable=True),
        # Internal staff writing. `app_sentiment` holds no grant on this table, so
        # it can never reach the sentiment pipeline (§7).
        sa.Column("incident_notes", sa.Text(), nullable=True),
        sa.Column("credit_issued_amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("created_by_user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("incident_id", name="pk_incidents"),
        sa.CheckConstraint(
            "incident_type IN ('missed_sla', 'wrong_dispatch_info', "
            "'repeat_visit_required', 'technician_conduct', 'equipment_damage', "
            "'billing_dispute', 'other')",
            name="ck_incidents_incident_type",
        ),
        sa.CheckConstraint(
            "incident_status IN ('open', 'investigating', 'resolved', 'closed')",
            name="ck_incidents_incident_status",
        ),
        sa.CheckConstraint("severity IN ('low', 'medium', 'high')", name="ck_incidents_severity"),
        sa.CheckConstraint(
            "root_cause_category IN ('dispatch_error', 'technician_error', "
            "'equipment_failure', 'client_site_issue', 'communication_breakdown', "
            "'other')",
            name="ck_incidents_root_cause_category",
        ),
        sa.CheckConstraint(
            "credit_issued_amount >= 0",
            name="ck_incidents_credit_issued_amount_non_negative",
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["service_requests.request_id"],
            name="fk_incidents_request_id_service_requests",
        ),
        sa.ForeignKeyConstraint(
            ["attributed_technician_id"],
            ["technicians.technician_id"],
            name="fk_incidents_attributed_technician_id_technicians",
        ),
        sa.ForeignKeyConstraint(
            ["reported_by_contact_id"],
            ["contacts.contact_id"],
            name="fk_incidents_reported_by_contact_id_contacts",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["internal_users.user_id"],
            name="fk_incidents_created_by_user_id_internal_users",
        ),
    )
    op.create_index("ix_incidents_request_id", "incidents", ["request_id"])
    op.create_index(
        "ix_incidents_incident_type_reported_at",
        "incidents",
        ["incident_type", "reported_at"],
    )

    op.create_table(
        "service_feedback",
        sa.Column("feedback_id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("request_id", sa.BigInteger(), nullable=False),
        sa.Column("incident_id", sa.BigInteger(), nullable=True),
        sa.Column("submitted_by_contact_id", sa.BigInteger(), nullable=False),
        sa.Column("submitted_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("rating", sa.SmallInteger(), nullable=True),
        # The customer's own words. Excluded from `app_reporting`'s column-level
        # grant in the following migration.
        sa.Column("feedback_text", sa.Text(), nullable=True),
        sa.Column("response_channel", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("feedback_id", name="pk_service_feedback"),
        sa.CheckConstraint(
            "response_channel IN ('email_survey', 'sms_survey', 'phone_followup', 'portal')",
            name="ck_service_feedback_response_channel",
        ),
        # NULL passes, which is correct — some respondents leave text only.
        sa.CheckConstraint("rating >= 1 AND rating <= 5", name="ck_service_feedback_rating_range"),
        sa.UniqueConstraint("request_id", name="uq_service_feedback_request_id"),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["service_requests.request_id"],
            name="fk_service_feedback_request_id_service_requests",
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.incident_id"],
            name="fk_service_feedback_incident_id_incidents",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_contact_id"],
            ["contacts.contact_id"],
            name="fk_service_feedback_submitted_by_contact_id_contacts",
        ),
    )
    op.create_index("ix_service_feedback_submitted_at", "service_feedback", ["submitted_at"])

    # ----------------------------------------------------------------- #
    # §4 Ground-truth tables — generator and eval only
    # ----------------------------------------------------------------- #
    op.create_table(
        "sentiment_labels",
        sa.Column("feedback_id", sa.BigInteger(), nullable=False),
        sa.Column("true_sentiment", sa.String(length=32), nullable=False),
        sa.Column("label_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column(
            "is_sarcastic",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("feedback_id", name="pk_sentiment_labels"),
        sa.CheckConstraint(
            "true_sentiment IN ('positive', 'neutral', 'negative', 'mixed')",
            name="ck_sentiment_labels_true_sentiment",
        ),
        sa.ForeignKeyConstraint(
            ["feedback_id"],
            ["service_feedback.feedback_id"],
            name="fk_sentiment_labels_feedback_id_service_feedback",
        ),
    )

    op.create_table(
        "generation_parameters",
        sa.Column("param_key", sa.String(length=100), nullable=False),
        sa.Column("param_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("param_group", sa.String(length=32), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "generated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("param_key", name="pk_generation_parameters"),
        sa.CheckConstraint(
            "param_group IN ('volume', 'incidents', 'sentiment', 'billing', 'anomalies')",
            name="ck_generation_parameters_param_group",
        ),
    )


def downgrade() -> None:
    op.drop_table("generation_parameters")
    op.drop_table("sentiment_labels")

    op.drop_index("ix_service_feedback_submitted_at", table_name="service_feedback")
    op.drop_table("service_feedback")

    op.drop_index("ix_incidents_incident_type_reported_at", table_name="incidents")
    op.drop_index("ix_incidents_request_id", table_name="incidents")
    op.drop_table("incidents")

    op.drop_index("ix_archived_requests_completed_at", table_name="archived_requests")
    op.drop_table("archived_requests")

    op.drop_index("ix_service_requests_parent_request_id", table_name="service_requests")
    op.drop_index("ix_service_requests_request_status", table_name="service_requests")
    op.drop_index(
        "ix_service_requests_account_id_scheduled_datetime", table_name="service_requests"
    )
    op.drop_index("ix_service_requests_scheduled_datetime", table_name="service_requests")
    op.drop_table("service_requests")

    op.drop_table("technician_skills")
    op.drop_table("locations")
    op.drop_table("contacts")
    op.drop_table("technicians")
    op.drop_table("internal_users")
    op.drop_table("accounts")
