"""Pydantic contracts shared across services.

Pydantic only, never ORM models (ADR-026): a tool's input/output shape and a table's
column structure change for different reasons. No dependency on `db_models`, so an
agent container that must not touch the database never installs it.
"""

from __future__ import annotations

from .forecast import (
    FORECAST_SLICES,
    HORIZON_BANDS,
    MAX_HISTORY_WEEKS,
    MAX_HORIZON_WEEKS,
    BandVerdict,
    ForecastAnswer,
    ForecastRequest,
    ForecastSlice,
    ForecastUnsupported,
    ForecastWeek,
    HistoryWeek,
    HorizonBand,
    VolumeForecast,
    VolumeHistory,
    band_of,
)
from .incidents import (
    MAX_COUNT_GROUPS,
    UNATTRIBUTED,
    GroupCount,
    IncidentGroupBy,
    IncidentSummary,
    SeverityCounts,
)
from .metrics import (
    MAX_GROUPS,
    FirstTimeFixResult,
    GroupBy,
    GroupRate,
    IncidentRateResult,
    SlaComplianceResult,
    rate_string,
)
from .repeats import (
    MAX_ACCOUNT_MATCHES,
    MAX_REPEAT_GROUPS,
    MAX_TECHNICIAN_MATCHES,
    MIN_GROUP_JOBS,
    AccountMatch,
    AccountMatches,
    JobsRepeated,
    RepeatBy,
    RepeatDriversResult,
    RepeatGroup,
    TechnicianMatch,
    TechnicianMatches,
)
from .reporting import (
    DATASET_WINDOW_END,
    DATASET_WINDOW_START,
    Metric,
    ReportingAnswer,
    ReportingRequest,
    RequestGroupBy,
)
from .routing import Domain, Route, RouteDecision
from .sentiment import (
    MAX_EXAMPLES,
    MAX_SPAN_DAYS,
    SENTIMENT_LABELS,
    Bucket,
    BucketCounts,
    Coverage,
    FeedbackExample,
    FeedbackExamples,
    LabelCounts,
    LabelShares,
    SentimentAnswer,
    SentimentLabel,
    SentimentRequest,
    SentimentSummary,
    SiteRegion,
    TrendResult,
    TrendVerdict,
    UnsupportedDimension,
)

__all__ = [
    "MAX_COUNT_GROUPS",
    "UNATTRIBUTED",
    "GroupCount",
    "IncidentGroupBy",
    "MAX_REPEAT_GROUPS",
    "MAX_ACCOUNT_MATCHES",
    "MAX_TECHNICIAN_MATCHES",
    "MIN_GROUP_JOBS",
    "JobsRepeated",
    "RepeatBy",
    "RepeatDriversResult",
    "RepeatGroup",
    "AccountMatch",
    "AccountMatches",
    "TechnicianMatch",
    "TechnicianMatches",
    "FORECAST_SLICES",
    "HORIZON_BANDS",
    "MAX_HISTORY_WEEKS",
    "MAX_HORIZON_WEEKS",
    "BandVerdict",
    "ForecastAnswer",
    "ForecastRequest",
    "ForecastSlice",
    "ForecastUnsupported",
    "ForecastWeek",
    "HistoryWeek",
    "HorizonBand",
    "VolumeForecast",
    "VolumeHistory",
    "band_of",
    "MAX_EXAMPLES",
    "MAX_SPAN_DAYS",
    "SENTIMENT_LABELS",
    "Bucket",
    "BucketCounts",
    "Coverage",
    "FeedbackExample",
    "FeedbackExamples",
    "LabelCounts",
    "LabelShares",
    "SentimentAnswer",
    "SentimentLabel",
    "SentimentRequest",
    "SentimentSummary",
    "SiteRegion",
    "TrendResult",
    "TrendVerdict",
    "UnsupportedDimension",
    "DATASET_WINDOW_END",
    "DATASET_WINDOW_START",
    "MAX_GROUPS",
    "Domain",
    "FirstTimeFixResult",
    "GroupBy",
    "GroupRate",
    "IncidentRateResult",
    "IncidentSummary",
    "Metric",
    "RequestGroupBy",
    "SlaComplianceResult",
    "rate_string",
    "ReportingAnswer",
    "ReportingRequest",
    "Route",
    "RouteDecision",
    "SeverityCounts",
]
